Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -630,6 +630,186 @@ fun_drop() {
 	}
 
 
+	inst_ssl5() {
+    if netstat -nltp | grep 'stunnel5' 1>/dev/null 2>/dev/null; then
+        [[ $(netstat -nltp | grep 'stunnel5' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel5 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
+        echo -e "\E[44;1;37m              GERENCIAR SSL STUNNEL5               \E[0m"
+        echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sslt"
+        echo ""
+        echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mALTERAR PORTA SSL TUNNEL\033[0m"
+        echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVER SSL TUNNEL\033[0m"
+        echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+        echo ""
+        echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+        read resposta
+        echo ""
+        [[ "$resposta" = '1' ]] && {
+            echo -ne "\033[1;32mQUAL PORTA DESEJA ULTILIZAR \033[1;33m?\033[1;37m "
+            read porta
+            echo ""
+            [[ -z "$porta" ]] && {
+                echo ""
+                echo -e "\033[1;31mPorta invalida!"
+                sleep 2
+                clear
+                fun_conexao
+            }
+            verif_ptrs $porta
+            echo -e "\033[1;32mALTERANDO PORTA SSL TUNNEL!"
+            var2=$(grep 'accept' /etc/stunnel/stunnel.conf | awk '{print $NF}')
+            sed -i "s/\b$var2\b/$porta/g" /etc/stunnel/stunnel.conf >/dev/null 2>&1
+            echo ""
+            fun_bar 'sleep 2'
+            echo ""
+            echo -e "\033[1;32mREINICIANDO SSL TUNNEL!\n"
+            fun_bar 'service stunnel5 restart' '/etc/init.d/stunnel5 restart'
+            echo ""
+            netstat -nltp | grep 'stunnel5' >/dev/null && echo -e "\033[1;32mPORTA ALTERADA COM SUCESSO !" || echo -e "\033[1;31mERRO INESPERADO!"
+            sleep 3.5s
+            clear
+            fun_conexao
+        }
+        [[ "$resposta" = '2' ]] && {
+            echo -e "\033[1;32mREMOVENDO O  SSL TUNNEL !\033[0m"
+            del_ssl() {
+                service stunnel5 stop
+                make -C /usr/local/src/stunnel-5.72 uninstall
+                rm -rf /usr/local/src/stunnel-5.72
+                rm -rf /etc/stunnel/stunnel.conf
+                rm -rf /etc/default/stunnel5
+                rm -rf /etc/stunnel/cert.cert
+                rm -rf /etc/stunnel/key.key
+            }
+            echo ""
+            fun_bar 'del_ssl'
+            echo ""
+            echo -e "\033[1;32mSSL TUNNEL REMOVIDO COM SUCESSO!\033[0m"
+            sleep 3
+            fun_conexao
+        }
+    else
+        clear
+        echo -e "\E[44;1;37m              INSTALAR SSL STUNNEL5               \E[0m"
+        echo ""
+        echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL PADRÃO\033[0m"
+        echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALAR SSL TUNNEL WEBSOCKET\033[0m"
+        echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mVOLTAR\033[0m"
+        echo ""
+        echo -ne "\033[1;32mOQUE DESEJA FAZER \033[1;33m?\033[1;37m "
+        read resposta
+        echo ""
+        if [[ "$resposta" = '1' ]]; then
+            portssl='22'
+        elif [[ "$resposta" = '2' ]]; then
+            portssl='80'
+        elif [[ "$resposta" = '0' ]]; then
+            echo -e "\033[1;31mRetornando...\033[0m"
+            sleep 3
+            fun_conexao
+        else
+            echo ""
+            echo -e "\033[1;31mOpcao invalida !\033[0m"
+            sleep 1
+            inst_ssl
+        fi
+        clear
+        echo -e "\E[44;1;37m           INSTALADOR SSL TUNNEL             \E[0m"
+        echo -e "\n\033[1;33mVC ESTA PRESTES A INSTALAR O SSL TUNNEL !\033[0m"
+        echo ""
+        echo -ne "\033[1;32mDESEJA CONTINUAR \033[1;31m? \033[1;33m[s/n]:\033[1;37m "
+        read resposta
+        [[ "$resposta" = 's' ]] && {
+            echo -e "\n\033[1;33mDEFINA UMA PORTA PARA O SSL TUNNEL !\033[0m"
+            echo ""
+            read -p "$(echo -e "\033[1;32mQUAL PORTA DESEJA UTILIZAR? \033[1;37m")" -e -i 443 porta
+            [[ -z "$porta" ]] && {
+                echo ""
+                echo -e "\033[1;31mPorta invalida!"
+                sleep 3
+                clear
+                fun_conexao
+            }
+            verif_ptrs $porta
+            echo -e "\n\033[1;32mINSTALANDO O SSL TUNNEL !\033[1;33m"
+            echo ""
+            fun_install_stunnel() {
+                apt-get update -y
+                apt-get install -y build-essential libssl-dev
+                cd /usr/local/src
+                curl -O https://www.stunnel.org/downloads/stunnel-5.72.tar.gz
+                tar xvf stunnel-5.72.tar.gz
+                cd stunnel-5.72
+                ./configure
+                make
+                make install
+                cd $HOME
+            }
+            fun_bar 'fun_install_stunnel'
+            echo -e "\n\033[1;32mCONFIGURANDO O SSL TUNNEL !\033[0m"
+            echo ""
+            ssl_conf() {
+                echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${portssl}\naccept = ${porta}" >/etc/stunnel/stunnel.conf
+            }
+            fun_bar 'ssl_conf'
+            echo -e "\n\033[1;32mCRIANDO CERTIFICADO !\033[0m"
+            echo ""
+            ssl_certif() {
+                crt='EC'
+                openssl genrsa -out key.pem 2048 >/dev/null 2>&1
+                (
+                    echo $crt
+                    echo $crt
+                    echo $crt
+                    echo $crt
+                    echo $crt
+                    echo $crt
+                    echo $crt
+                ) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
+                cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
+                rm key.pem cert.pem >/dev/null 2>&1
+                sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel5
+            }
+            fun_bar 'ssl_certif'
+            echo -e "\n\033[1;32mINICIANDO O SSL STUNNEL5 !\033[0m"
+            echo ""
+            fun_finssl() {
+                service stunnel5 restart
+                service ssh restart
+                /etc/init.d/stunnel5 restart
+            }
+            fun_bar 'fun_finssl' 'service stunnel5 restart'
+            echo -e "\n\033[1;32mSSL STUNNEL5 INSTALADO COM SUCESSO !\033[1;31m PORTA: \033[1;33m$porta\033[0m"
+            sleep 1
+            clear
+            echo -e "Corrigindo SSL CLARO"
+            cd /etc/stunnel/
+            rm -rf stunnel.conf
+            rm -rf stunnel.pem
+            wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/cert
+            wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/key
+            wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/main/Install/stunnel
+            mv cert cert.pem
+            mv key key.pem
+            mv stunnel stunnel.conf
+            chmod 777 cert.pem
+            chmod 777 key.pem
+            chmod 777 stunnel.conf
+            service stunnel5 restart
+            cd $HOME
+            clear
+            echo -e "Corrigido"
+            sleep 2
+            fun_conexao
+        } || {
+            echo -e "\n\033[1;31mRetornando...\033[0m"
+            sleep 2
+            clear
+            fun_conexao
+        }
+    fi
+}
+
+
         ws_ssl() {
 		rm -rf /root/*   && wget https://raw.githubusercontent.com/PhoenixxZ2023/PLUS/refs/heads/main/Modulos/ws_ssl_auto.sh && chmod +x ws_ssl_auto.sh && ./ws_ssl_auto.sh
 		sleep 3
@@ -2127,7 +2307,7 @@ echo -e "\033[01;31m┣━━━━━━━━━━━━━━━━━━━
 			} || {
 				sts3="\033[1;31m○ "
 			}
-			[[ -e "/usr/local/etc/stunnel/stunnel.conf" ]] && {
+			[[ -e "/etc/stunnel/stunnel.conf" ]] && {
 				echo -e "\033[01;31m┃\033[1;32mSERVICO: \033[1;33mSSL STUNNEL5 \033[1;32mPORTA: \033[1;37m$(netstat -nplt | grep 'stunnel5' | awk {'print $4'} | cut -d: -f2 | xargs)\033[01;31m                       \033[0m"
 				sts15="\033[1;32m◉ "
 			} || {
